# This is a basic workflow to help you get started with Actions

name: CI

on: push

jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
    - name: Step one
    - uses: actions/checkout@v2
    - name: Step two
      run: env | sort

  job2:
    name: Second Job
    runs-on: windows-latest
    steps:
    - name: Step one
    - uses: actions/checkout@v2
    - name: Step two
      run: "Get-ChildItem Env: | Sort-Object Name"